### ISSUE TITLE
Rotated orientation of the chord diagram

### ISSUE THREAD

**Issue by Anomalion** [bragefuglseth/fretboard#39] opened 2023-11-02 10:07 UTC
I’m used to reading chord diagrams rotated 90° counter-clockwise relative to how they are displayed in fretboard now.
Since that made it much easier for me to rad them quickly, I would suggest adding an option to rotate the diagrams (permanently).

**Comment by bragefuglseth** [comment] 2023-11-02 10:17
Hi, and thanks for your suggestion! This seems like a duplicate of #9, and is not planned at the moment.

**Closed** 2023-11-03 08:04 UTC
